#!/usr/bin/env bash

set -ex

TARGET_HOST=${1:-ya_cloud_world_bot}
REMOTE_WORKDIR=${2:-/home/dbrusenin/world_bot}

docker-compose -f docker-compose.prod.yaml build
docker-compose -f docker-compose.prod.yaml push

./deploy/make_deploy_docker_compose docker-compose.prod.yaml deploy/bundle/docker-compose.yaml
cp .env.prod deploy/bundle/.env.prod

scp -r deploy/bundle/. dbrusenin@$TARGET_HOST:$REMOTE_WORKDIR

ssh $TARGET_HOST "$REMOTE_WORKDIR/pull"
ssh $TARGET_HOST "$REMOTE_WORKDIR/down"
ssh $TARGET_HOST "$REMOTE_WORKDIR/up"
