version: '3'

services:

  bot:
    platform: linux/x86_64
    image: cr.yandex/crparlvq5pji2gn67f8s/deimvis/wb_bot:latest
    container_name: wb_bot
    env_file:
      - .env
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 5s

  db:
    platform: linux/x86_64
    image: mirror.gcr.io/postgres:15.2
    container_name: wb_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5434:5432
    env_file:
      - .env


volumes:
  postgres_data:
