#!/usr/bin/env python3
import argparse
import logging
import os
import sys
from psycopg2.extensions import AsIs

sys.path.append('.')
from src.utils.postgres import PostgresConnection, create_database, drop_database


logging.basicConfig(level=logging.DEBUG)


def parse_args():
    parser = argparse.ArgumentParser(description='Initialize db (Postgres)')
    parser.add_argument('--drop', action='store_true')
    return parser.parse_args()


def init_db():
    with PostgresConnection(
                host=os.getenv('DB_HOST'),
                port=os.getenv('DB_PORT'),
                user=os.getenv('DB_USER'),
                password=os.getenv('DB_PASSWORD'),
                db_name=os.getenv('DB_NAME'),
            ) as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """CREATE TABLE IF NOT EXISTS %s (
                        id BIGSERIAL PRIMARY KEY,
                        text TEXT,
                        author VARCHAR(255) DEFAULT '—'::varchar,
                        language VARCHAR(3),
                        source VARCHAR,
                        UNIQUE(author, text)
                    )
                """,
                (AsIs("quote"),)
            )
            cursor.execute(
                """CREATE TABLE IF NOT EXISTS %s (
                        id BIGSERIAL PRIMARY KEY,
                        chat_id      BIGINT     NOT NULL,
                        base_weekday SMALLINT,
                        base_hour    SMALLINT   NOT NULL,
                        base_minute  SMALLINT   NOT NULL,
                        timezone     VARCHAR    NOT NULL,
                        language     VARCHAR(3) NOT NULL,
                        creation_ts  BIGINT,
                        _raw         VARCHAR    NOT NULL
                    )
                """,
                (AsIs("quotes_subscription"),)
            )
            cursor.execute(
                '''CREATE TABLE IF NOT EXISTS "%s" (
                        id BIGINT PRIMARY KEY,
                        username TEXT,
                        first_name TEXT,
                        last_name TEXT
                    )
                ''',
                (AsIs("user"),)
            )
    logging.info('Database "{}" has been initialized'.format(os.getenv('DB_NAME')))


def create_db():
    with PostgresConnection(
                host=os.getenv('DB_HOST'),
                port=os.getenv('DB_PORT'),
                user=os.getenv('DB_USER'),
                password=os.getenv('DB_PASSWORD'),
                db_name='postgres',
            ) as conn:
        create_database(conn, os.getenv('DB_NAME'), if_not_exists=True)
    logging.info('Database "{}" has been created'.format(os.getenv('DB_NAME')))


def drop_db():
    with PostgresConnection(
                host=os.getenv('DB_HOST'),
                port=os.getenv('DB_PORT'),
                user=os.getenv('DB_USER'),
                password=os.getenv('DB_PASSWORD'),
                db_name='postgres',
            ) as conn:
        drop_database(conn, os.getenv('DB_NAME'))
    logging.info('Database "{}" has been dropped'.format(os.getenv('DB_NAME')))


def main():
    args = parse_args()
    if args.drop:
        drop_db()
        create_db()
    init_db()


if __name__ == '__main__':
    main()
